### ISSUE TITLE
First offline run failed

### ISSUE THREAD

**Issue by boardfish** [andrewfstratton/quando#174]
Readme steps failed on Ubuntu 19.04 at [step 3](https://github.com/andrewfstratton/quando#setting-up-quando-for-first-time-for-offline-and-local).

@andrewfstratton, I remember you showed me to run `pouchdb` separately yesterday - is that the preferred method now? If so, I'll update the readme. Would it be alright for me to submit it as a PR for [Hacktoberfest](https://hacktoberfest.digitalocean.com)?

```
┌─[si@yang] - [~/code/quando] - [4263]
└─[$] npm run quando                                                                                                                                             [11:22:11]
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1364:7)
    at Object.<anonymous> (/home/si/code/quando/server.js:48:19)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1255:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quando@0.8.20190924 quando: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quando@0.8.20190924 quando script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/si/.npm/_logs/2019-10-11T10_23_07_765Z-debug.log
```

**Comment by andrewfstratton** [comment]
Hi Simon
 Looks like you already have an http server running on port 80...
